linters:
  disable:
    - scopelint
    - goerr113
    - wrapcheck
    - funlen
    - maligned
    - golint
    - interfacer
    - gomnd
    - gochecknoglobals
    - exhaustivestruct
    - lll
    - wsl
    - thelper
    - testpackage
    - typecheck
    - nlreturn
    - nilnil
    - varnamelen
    - forcetypeassert
  presets:
    - bugs
    - comment
    - complexity
    - error
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused
linters-settings:
  cyclop:
    max-complexity: 15
    skip-tests: true
  revive:
    rules:
      - name: unexported-return
        disabled: true
  maintidx:
    under: 10
