name: Attach Binary to Release

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - run: make build
      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: ./bin/blast
          tag_name: ${{ github.event.release.tag_name }}
